### ISSUE TITLE
VNC / Microphone issue

### ISSUE THREAD

**Issue by randomuser1234** [manwhoami/Bella#10]
I am having great success with Bella however there are two issues I continuously seem to run into.

1. I cannot get the VNC session to work. It gives me an IP and all that but I guess I am just confused on how it all works. Can you give a walkthrough on the VNC option? 

2. The microphone always fails by saying could  not reach the launcher or something (sorry not able to test at the moment). Any idea why? I forwarded the port and the traffic seems to not be blocked on either end. 

If it matters this is all over the internet and not local.

Thanks!

**Comment by manwhoami** [comment]
Glad to hear. Now that you mention it, if you are using a Linux machine for the Control Center, the microphone will not stream, because the decoder for the audio is a macOS only binary. I am working on a solution for this. A similar, but immediately fixable, problem would also happen with VNC if you are using a control center. 

VNC & microphone should be the only things that at the moment will cause issues on a Linux CC.

**Comment by randomuser1234** [comment]
That's good to hear! Thank you for explaining and I can't wait for it to be fixed! 

One more question:

How does the persistence work with this? I know it's automatic but I'm confused when it's possible. If I am on a user with "Admin" access will persistence take hold automatically when the payload is dropped initially? I tested the get_system option on a very old Yosemite laptop and it worked great and I know persistence worked on that. When I upgraded it to Sierra the get_system was not available anymore. I guess to break down my question... If a user with admin permissions connects to CC will persistence take hold automatically? 

Thanks!

**Comment by manwhoami** [comment]
Well, there are basically three things that can happen [short explanation] to run Bella as root.

When you run `get_root`

1. That happened on Yosemite because of Bella's built in Local Privilege Escalation Exploit for macOS <= 10.11.3. If you run `get_root` on any system <= 10.11.3, Bella will automatically escalate to root. Nothing else is required. Support for > 10.11.3 may be given in the future, depending on what LPE exploits are reported.

2. If you are running > 10.11.3, then you can run `user_pass_phish`, to phish the user for their password. If this is a personal laptop, then the user is *highly* likely to be a local administrator. What a "local administrator" means, is that if you get that user's password, then you can run any function on the system as root. If you phish the user's password, Bella will use it to escalate to root [if they're a local admin]. The only case that this may not work in, is in a corporate, domain based, IT managed environment.

Otherwise:

1. If you install Bella as root [either from single user mode, or just running in a root shell], then Bella will be installed as root automatically, and you do not need to worry about `get_root`.
