### ISSUE TITLE
when my ip changes can't find my target

### ISSUE THREAD

**Issue by Scriptkidy** [manwhoami/Bella#37]
I'm sorry i know this not your fault i'm a noobie so please help me
when my ip changes than i can't get into bella
on the target i need to delete .Bella
in `./BUILDER Bella.py` i leave all to default but in `Where should Bella connect to: my computer ip`
please tell me what i am doing wrong.

**Comment by manwhoami** [comment]
Right ... Bella connects to a preprogrammed IP address. If you address changes, Bella will not be able to connect to you. It has know way of knowing what computer you're on, so that is why the IP address of the control center is permanent [unless you update the host with a new version of bella with a new IP address]. No worries on the question, but this is a pretty straight forward networking concept that can be resolved with a quick google search.

**Comment by Scriptkidy** [comment]
thanks sorry I'm a noobie
