### ISSUE TITLE
Port Check Error

### ISSUE THREAD

**Issue by BlackDeveraux** [manwhoami/Bella#39]
I've been testing Bella out on local ranges so far, with a DNS setup pointed to a 192.168.x.x address. 
I tried setting up a solution that would work over the internet, and it worked, until I try and scan/ping my IP for Port 4545. 

The control center runs as it normally would, but when I scan for the port 4545 the control center crashes and throws this error:

`EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "./Control Center.py", line 683, in <module>
    main()
  File "./Control Center.py", line 201, in main
    raise e
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)`

Any thoughts?

**Comment by mineo210** [comment]
this happens also if you try to connect to the port via the browser, I think it crashes since it not supposed to be connected that way and if nmap scans it, it tries connecting I guess.. How I've made it work over the Internet is by building the payload with my public ip or dns server and then port forward all the ports that are recommended inside of the README.md, later I check if the port works by checking on a website I think is called "can you see me" something. :)

**Comment by BlackDeveraux** [comment]
Yeah I bet it's not built to handle such a request, but even then, I don't think the Control Center should terminate because of this?

**Comment by mineo210** [comment]
this happens on nc too.. or it will not respond and stop work

**Comment by mineo210** [comment]
netcat*

**Comment by manwhoami** [comment]
Yes, the CC expects a very particularly crafted request. If it is crashing, that means the port is being forwarded successfully, the control center just doesn't know how to handle the forwarded request.

You are just testing if the port is forwarded yes?

**Comment by BlackDeveraux** [comment]
@manwhoami 
Yes, I was pinging the port for testing purposes. 
And the set-up does work, and latency doesn't seem to be too big a problem!
