### ISSUE TITLE
sed: can't read : No such file or directory

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#4]
When I try to build bella, I get this error
```
Synthx@Debian:~/Bella$ sudo ./BUILDER Bella.py
[sudo] password for Synthx:
What should the Launch Agent named? Default is [com.apple.Bella]: com.oracle.java.Java-Updatr
Where should Bella be stored in ~/Library/? Default is [Containers/.bella]: ~/Library/LaunchAgents
Where should Bella connect to: MY.IP.HERE
What port should Bella connect on [Default is 4545]: 2000
Configuring your Bella installation
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Error inserting config variables!
Synthx@Debian:~/Bella$
```

**Comment by manwhoami** [comment]
You appear to be building on a non-macOS machine. This is not supported yet.

**Comment by xSynthx** [comment]
So could I build Bella on my mac and then transfer the files to my VPS (Debian)? 
The main reason I ask is because I can't port forward on my wifi

**Comment by manwhoami** [comment]
So the builder is not compatible with Linux. If you build on macOS, you may be able to run the Control Center on a linux box. I have not tested with Linux yet, so I am not sure if it will work or not. I will have a patch for the Control Center and Builder to work on Linux within in a few days. 

I will post here when that is done.

**Comment by xSynthx** [comment]
It did not work :( I cant wait for you to update it so we can build and run it on debian/linux! Thank you so very much :) :) :)

**Comment by manwhoami** [comment]
I have added support for Linux for both the builder and control center. Let me know how it works.

**Comment by xSynthx** [comment]
Okay, when the builder makes the payload on linux machine, does it make the payload a linux one, or a mac payload?

**Comment by xSynthx** [comment]
and also, is there a way that I can contact you in a quicker way? 
Twitter: _Synthx
Discord: کyпTђҳ ムツヲ#1356
Chat live on my website: http://synthx.pw

**Comment by xSynthx** [comment]
Well, I generated the payload on my VPS (Debian), and downloaded the folder to my desktop, ran the command thing, and it opened terminal and did everything, I checked to see the launchagents, it was there, then I checked in Containers, it was also there, but when I would go onto my VPS, my client (ME) isnt there. I created a payload on my mac, and had it connect back to my mac, ran the payload and it worked :/ I am currently at school and am on a VPN, *my school blocks ssh connections which is why I use a vpn, besides unblocking websites* I will retry when I get home.

**Comment by xSynthx** [comment]
I also have something else, when it says found clients, I get a new line, but its just blank?!? am I supposed to run a command or something?
![screen shot 2017-02-14 at 12 11 19 pm](https://cloud.githubusercontent.com/assets/25438703/22942434/2e47526c-f2af-11e6-8dbf-4d87229d3980.png)

**Comment by manwhoami** [comment]
Regardless of where you run the Builder, it makes a payload for macOS. Bella is integrated deeply with macOS internals, and I have no plans (at the moment) for porting the actual payload over to linux.

The Control Center will run any an *NIX based machine, so Linux and macOS. 

There are two possible reasons why Bella is not connecting to your VPS:
1.) Your VPS is blocking Bella through its firewall. Does your VPS allow port forwarding? If it does not, then you will not be able to use the Control Center on it. Bella will try to connect to your VPS's IP address, but your VPS will bounce the connection if port 4545 [or whatever you set it to] is not opened on your VPS's firewall. It sounds like this is the issue you are experiencing. 

To quickly check your VPS's firewall configuration, try the following on your VPS in a command line:

`python -m SimpleHTTPServer 7777`

Then, in a web browser on a computer that is NOT your VPS, type this in the address bar:
`YOUR_VPS_IP:7777`. If that connection is refused, your VPS has a firewall. Go configure it, and if you can't configure it, switch to a VPS that will let you. Otherwise the Control Center will NOT work on your VPS.

2.) You have the wrong IP address :D

Let me know.

**Comment by xSynthx** [comment]
1) I know for a matter of fact this is not the problem as I have used EggShell, and I have also used pupy and they have both been successful in working, I also have every single port open especially when I run pupy, eggshell, nc, and bella with `sudo` I have to use it with `sudo` or else it wont let me connect, I think it drops a error like `Cannot bind on 0.0.0.0:0` something like that.

2) I know for a matter of fact its the right IP, because I copied it from a working EggShell, and pupy payload! :)

**Comment by manwhoami** [comment]
Sorry, I think I misunderstood. So you can connect? When you see found clients, press `CTRL-C` . you should then get a prompt that says `Enter ID to initiate connection`. Then type in the number of the client you want. You should then get something like this
```
Accepting Connection from [Your-Bella-Machine] at [127.0.0.1]
Last Connected: Day, Month DD YYYY at HH:MM:SS PM -- UPTIME
[User@Your-Bella-Machine]-[~] 
```
where you can start entering commands

**Comment by xSynthx** [comment]
okay, cool, I just didnt understand what to do when the client connected *maybe add that to the README.md*!

**Comment by manwhoami** [comment]
It's at the beginning of step 5 :)

**Comment by xSynthx** [comment]
Was it always there? If so, I read over it. *highly possible*

**Comment by manwhoami** [comment]
GitHub has version control, so you can actually see any edits if you go to "commits". Been there since release. Happens to the best of us!

**Comment by xSynthx** [comment]
well, I didnt even check that, I meant to, but I forget things VERY quickly :) thanks for everything!
