### ISSUE TITLE
mike_stream doesn't work

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#41]
I mean it works but I can't hear what the victim says..

**Comment by manwhoami** [comment]
I am unable to reproduce this issue. The only thing that I can think of that would be causing this is some sort of feedback loop due to proximity. Is the control center system closer than say, 10 feet to the target?

Also, details about both the control center and the target systems (operating system, hardware) would be helpful in troubleshoot this.

**Comment by mineo210** [comment]
@manwhoami the victim uses a early 2013 version of the macbook air 11 inch and has the latest version of osx (10.12.3) other than that others victims has the same issue they are right in front of the webcam even tho I can see that they are talking to someone inside of for example discord.. and instead i get just "ear rape and mumble etc"

**Comment by manwhoami** [comment]
Hmm. I can try to test out on more machines. It is unlikely that there is anything I could do about this, the microphone feature just captures all microphone input and sends it over the network. 

I will see what can cause interference. I get crystal clear streams on all the machines I have tested on so far, including a MB air.

**Comment by mineo210** [comment]
why do you keep editing the word "ear rape" XD
