### ISSUE TITLE
No password 

### ISSUE THREAD

**Issue by randomuser1234** [manwhoami/Bella#42]
I've noticed when a user does not have a password the user_pass_phish option will not work. Even when you use update_db_entry it will not allow you to enter nothing. 

One quick way to fix this would be to just test for no password with the get_root option.

Also, I could just be oblivious but is there a command to not exit the Control Center while also exiting the current target? Like how you can go back on meterpreter to view all currently accessible targets without fully disconnecting? I seem to have to just relaunch the Control Center every time I want to view the initial connection screen.

I also get errors when trying to use the set_client_name option. 
OperationalError: no such column: client_name

**Comment by ochsenjoch** [comment]
The problem is, that if the user has set no password, he will not be able to use "sudo", since UNIX simply doesn't like to have no passwords. You can test this by setting no password on your local user and try a sudo command in the terminal

**Comment by manwhoami** [comment]
Thank you @ochsenjoch . I will mess around with an account with no password to see if there is a way to gain admin access without it. 

@randomuser1234 in regards to the returning to the screen without disconnecting, see [this issue](https://github.com/manwhoami/Bella/issues/28#issuecomment-287966008) . I will add this feature shortly.

**Comment by manwhoami** [comment]
Okay, so if the user has no password, sudo is not possible. One little work around this, is to set a temporary password for the user, since we know the current one is ''.  Then, get sudo with this password, migrate Bella to root, then set the password for the user back to '' (blank). This is a few lines of code, but I will have to add a lot of error handling, so in the event that anything goes wrong, the user will not be locked out of their account (that would be very bad). 

Will post here when I am finished with adding support for blank password handling, and will also post here when I finish the feature to go back to the client selection screen without having to relaunch the control center.
