### ISSUE TITLE
suggestion - copy vs move

### ISSUE THREAD

**Issue by Skeyelab** [manwhoami/Bella#8]
Can you make it so if one was to place the generated Bella file on an external disk (USB key) and run it from there, it copies to the destination, as opposed to move it?

**Comment by manwhoami** [comment]
This is not an intended design feature of Bella. Its self installer / remover is part of the design.

If you would like to have this function, you can delete the following two lines from the builder:

```sed -i '' -e "s@development = True@development = False@" $BuildsPath/bella.py ```

```sed -i "s@development = True@development = False@" $BuildsPath/bella.py```

This will enable "developer" mode, which for the time being, copies bella instead of moving it.
